apiVersion: v1
kind: PersistentVolume
metadata:
  name: song-db-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /home/docker/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-db-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
