apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-storage-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/audio-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi