apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-depl
  labels:
    app: catalog-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-depl
  template:
    metadata:
      labels:
        app: catalog-depl
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "443"
    spec:
      containers:
      - name: catalog-depl
        image: ricardoandaluz/catalog:v73
        ports:
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: /liveness
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: REDIS_SENTINEL_HOST
          value: "redis-sentinel.default.svc.cluster.local"
        - name: REDIS_SENTINEL_PORT
          value: "26379"
        - name: REDIS_MASTER_NAME
          value: "mymaster"
        - name: KAFKA_SERVER
          value: "kafka-svc.default.svc.cluster.local:9092"
        volumeMounts:
        - name: audio-storage
          mountPath: /usr/share/nginx/html/audio
      volumes:
      - name: audio-storage
        persistentVolumeClaim:
          claimName: audio-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  labels:
    app: catalog-depl
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: catalog-depl
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
