apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-depl
  labels:
    app: catalog-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-depl
  template:
    metadata:
      labels:
        app: catalog-depl
    spec:
      containers:
      - name: catalog-depl
        image: ricardoandaluz/catalog:v39
        ports:
        - containerPort: 443
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: REDIS_SENTINEL_HOST
          value: "redis-0.redis"
        - name: REDIS_SENTINEL_PORT
          value: "26379"
        - name: KAFKA_SERVER
          value: "kafka-svc.default.svc.cluster.local:9092"
        volumeMounts:
        - name: audio-storage
          mountPath: /usr/share/nginx/html/audio
      volumes:
      - name: audio-storage
        persistentVolumeClaim:
          claimName: audio-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  labels:
    app: catalog-depl
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: catalog-depl
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80