apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: logging
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.14.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false