apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-depl
  labels:
    app: home-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-depl
  template:
    metadata:
      labels:
        app: home-depl
    spec:
      containers:
      - name: home-depl
        image: ricardoandaluz/home:v69
        ports:
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: /liveness
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: KAFKA_SERVER
          value: "kafka-svc.default.svc.cluster.local:9092"
        - name: CATALOG_URL
          value: "https://catalog-svc.default.svc.cluster.local:443"
        
        - name: HOME_URL
          value: "https://home-svc.default.svc.cluster.local:443"
        volumeMounts:
        - name: audio-storage
          mountPath: /usr/share/nginx/html/audio
      volumes:
      - name: audio-storage
        persistentVolumeClaim:
          claimName: audio-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: home-svc
  labels:
    app: home-depl
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: home-depl
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80