apiVersion: v1
kind: Namespace
metadata:
  name:  logging

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: logging
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.14.3
  count: 1
  elasticsearchRef:
    name: quickstart
